### ISSUE TITLE
Correcting the card content with encrypted content

### ISSUE THREAD

**Issue by rios0rios0** [rios0rios0/rios0rios0.github.io#1]
## Summary

Post preview cards on the home page display incorrectly for posts that use `jekyll-crypto` encryption (HTB write-ups for active machines). The card body either shows encrypted cipher-text blobs or appears empty due to `.cipher-text { display: none !important }`.

## Context

Some posts use `jekyll-crypto` to password-protect content (e.g., `posts/sec-ctf-htb-m-blunder/index.html` is 200KB due to encrypted content, vs. 33KB for the retired Traceback post). The CSS handles encryption UI:

```css
#password-wrapper { display: flex; border-radius: 1rem; ... }
.jekyll-crypto, .jekyll-crypto-preview, .jekyll-crypto-result { transition: opacity 4000ms }
.cipher-text { display: none !important }
```

On the home page (`index.html`), each post is rendered as a card with `.post-preview > .post-content > .caption`. For encrypted posts, the card preview likely shows the raw cipher-text or an empty body instead of a meaningful excerpt/gate message.

## Acceptance Criteria

- [ ] Ensure encrypted post cards show a meaningful preview (e.g., the "gate" message about needing the password)
- [ ] Ensure cipher-text is never visible in card previews
- [ ] Verify both encrypted posts (blunder, cache, admirer) and unencrypted posts (traceback) render correctly

## Relevant Files

- `index.html` — home page with post preview cards
- `posts/sec-ctf-htb-m-blunder/index.html` — encrypted post (200KB)
- `posts/sec-ctf-htb-m-cache/index.html` — encrypted post
- `assets/css/home.css` — `.jekyll-crypto`, `.cipher-text` styles
- `assets/css/post.css` — encryption-related styles
