### ISSUE TITLE
Fixing the navigation bar wrong behavior

### ISSUE THREAD

**Issue by rios0rios0** [rios0rios0/rios0rios0.github.io#3]
## Summary

The sidebar navigation bar (left panel: HOME, CATEGORIES, TAGS, TIMELINE, ABOUT ME) has incorrect behavior — the active indicator and/or scroll-hide/show behavior is broken.

## Context

The CSS uses hardcoded `top` offsets on a `::after` pseudo-element to slide the active indicator:

```css
#sidebar ul>li.active:nth-child(1)~li:last-child::after { top: -12.4rem; visibility: visible }
#sidebar ul>li.active:nth-child(2)~li:last-child::after { top: -9.1rem; visibility: visible }
/* ... up to nth-child(5) */
```

This is fragile — if `nav-item` heights change or items are added/removed, the hardcoded `top` values break. Additionally, `home.min.js` implements a hide-on-scroll-down / show-on-scroll-up pattern for `#topbar-wrapper` (`.topbar-up` / `.topbar-down` classes) that may interact incorrectly with the sidebar on mobile (where sidebar slides in via `transform: translateX(-260px)` and `#sidebar-trigger` toggle).

## Acceptance Criteria

- [ ] Fix the active indicator positioning to work dynamically instead of hardcoded `top` values
- [ ] Ensure topbar scroll hide/show doesn't break sidebar toggle on mobile (≤830px)
- [ ] Verify all 5 navigation items (HOME, CATEGORIES, TAGS, TIMELINE, ABOUT ME) show correct active state

## Relevant Files

- `assets/css/home.css` — sidebar and topbar CSS, active indicator pseudo-element
- `assets/css/post.css` — same sidebar/topbar patterns
- `assets/js/home.min.js` — sidebar toggle logic, topbar hide-on-scroll
