### ISSUE TITLE
Correcting to use a full body with content

### ISSUE THREAD

**Issue by rios0rios0** [rios0rios0/rios0rios0.github.io#5]
## Summary

The page body content area does not fill the full viewport height, leaving dead space below the content on certain screen sizes.

## Context

This is a pre-built Jekyll site using the Chirpy theme (v2.x) deployed via GitHub Pages. The repository stores compiled HTML output (no `_config.yml` or Jekyll source). The CSS uses a `min-height` calculation that subtracts an excessively large value:

```css
#main>div.row:first-child>div:first-child { min-height: calc(100vh - 3rem - 5rem - 35rem) }
#post-wrapper { min-height: calc(100vh - 3rem - 5rem - 35rem) !important }
```

The `35rem` subtraction is very large and causes the content area to not extend to the full page height, especially on smaller viewports.

## Acceptance Criteria

- [ ] Adjust the `min-height` calculations in `assets/css/home.css` and `assets/css/post.css` so the content fills the viewport
- [ ] Ensure the fix works across all page types (home, posts, tabs, categories, tags)
- [ ] Test on common viewport sizes (mobile, tablet, desktop)

## Relevant Files

- `assets/css/home.css` — homepage styles with `min-height` calculations
- `assets/css/post.css` — post page styles with same pattern
- `index.html` — home page layout
